name: createDist

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup Node
      uses: actions/setup-node@v3
    - run: npm ci
    - run: npm run build:libs

    - name: version core
      uses: nyaa8/package-version@v1
      with:
       path: './dist/@ajsf/core/package.json'  
    
    - name: dist core
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist_core
        FOLDER: ./dist/@ajsf/core_v{{ env.PACKAGE_VERSION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: dist bootstrap3
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist_bootstrap3
        FOLDER: ./dist/@ajsf/bootstrap3
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
    - name: version bootstrap4
      uses: nyaa8/package-version@v1
      with:
       path: 'ajsf/projects/ajsf-bootstrap4/package.json'         
   
    - name: dist_bootstrap4
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist_bootstrap4
        FOLDER: ./dist/@ajsf/bootstrap4_v${{ env.PACKAGE_VERSION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: version material
      uses: nyaa8/package-version@v1
      with:
       path: 'ajsf/projects/ajsf-material/package.json' 

    - name: dist material
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist_material_v${{ env.PACKAGE_VERSION }}
        FOLDER: ./dist/@ajsf/material
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   

        
        
